- CHANGELOG.rst
- learning_assistant/api.py
- learning_assistant/constants.py
- learning_assistant/serializers.py
- learning_assistant/urls.py
- learning_assistant/utils.py
- learning_assistant/views.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.in
- requirements/test.txt
- test_settings.py
- tests/test_utils.py
- tests/test_views.py
This PR contains support for an endpoint that accepts POST requests containing a message list. Access to the endpoint is gated by user enrollment or staff status, a course waffle flag, and an additional Django setting that defines a chat completion API URL. 
If all requirements for access to the endpoint are met, the message list is passed on to the chat completion API. The response from the chat completion API is then passed through as the response from the endpoint defined in the PR.
> feat: add endpoint to retrieve chat response

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/admin.py
- learning_assistant/views.py
The edx-platform functions imported require a course key to be passed in, not a course id. Passing in the course ID was causing a 500 error when making calls to the endpoint. I tested locally and the endpoint is able to make all the required checks prior to forwarding the request to the chat completion endpoint. 
As part of testing, I also needed to set up a course prompt, so I included the ability to add a course prompt via django admin to this PR.
> fix: course id should be converted to course key for edx-platform functions

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/views.py
- tests/test_views.py
This PR grants learners with an audit enrollment access to the learning assistant backend.
> feat: give audit learners access to la bot

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/utils.py
- learning_assistant/views.py
- tests/test_utils.py
To avoid going over the maximum amount of tokens allowed, we should reduce the user message list and send only the most recent messages that do not go over the number of allotted tokens.
> feat: use reduced message to avoid maxing out tokens

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/management/commands/set_course_prompts.py
- learning_assistant/management/commands/tests/test_set_course_prompts.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
- test_settings.py
This PR adds a management command that generates a new set of course prompts given a list of course ids.
> feat: add management command for course prompts

- learning_assistant/api.py
- learning_assistant/constants.py
- learning_assistant/platform_imports.py
- learning_assistant/text_utils.py
- tests/test_api.py
- tests/test_text_utils.py
In order to provide unit specific content to a prompt template, the content needs to be extracted from a given block. Pieces of this code have been taken from the ai_aside repository, specifically the `text_utils.py` file. 
Content from a block is retrieved using a pre-order traversal, meaning that all content will be returned in the order a learner would be viewing the content.
> feat: expose functionality to extract unit content

- CHANGELOG.rst
- learning_assistant/api.py
- learning_assistant/text_utils.py
- test_settings.py
- tests/test_api.py
In order to avoid multiple calls into modulestore for course content, the content should be cached on a per user, course, and unit usage key basis. The default TTL is set to 360 seconds, which was determined to be an appropriate amount of time after analyzing the duration of conversations typically had with the learning assistant.
> feat: cache unit content

- docs/decisions/0003-courseapp-use.rst
**Jira**: [COSMO-128](https://2u-internal.atlassian.net/browse/COSMO-128)
This commit adds an ADR to document our decision to use the edx-platform [CourseApp Django app](https://github.com/openedx/edx-platform/tree/master/openedx/core/djangoapps/course_apps) to register a Learning Assistant CourseApp plugin with the platform. The impact of this is that this feature will be exposed via the [CourseApp REST API](https://github.com/openedx/edx-platform/blob/master/openedx/core/djangoapps/course_apps/rest_api/v1/views.py#L80), and a card for this feature will appear on the [Pages & Resources page](https://github.com/openedx/frontend-app-course-authoring/tree/master/src/pages-and-resources).
> Add ADR for using the edx-platform CourseApp Django app.

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/toggles.py
- tests/test_api.py
This pull request adds a course waffle flag that will control whether or not course content is added to the prompt template. 
Because the toggle is defined outside of a function, an import error occurs at runtime if the CourseWaffleFlag class is not mocked out properly.
> feat: add course waffle flag for content integration

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/platform_imports.py
- learning_assistant/toggles.py
- learning_assistant/utils.py
- learning_assistant/views.py
- requirements/base.in
- requirements/base.txt
- requirements/ci.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/pip-tools.txt
- requirements/quality.txt
- requirements/test.txt
- test_settings.py
- tests/test_api.py
- tests/test_utils.py
- tests/test_views.py
Replace use of course specific prompts with a prompt template stored in a django setting.
> feat: integrate system prompt

- codecov.yml
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/platform_imports.py
- learning_assistant/views.py
- tests/test_api.py
- tests/test_views.py
**Jira**: [COSMO-161](https://2u-internal.atlassian.net/browse/COSMO-161)
This commit modifies the Learning Assistant access logic.
Previously, the chat view would return a 403 response code if the `learning_assistant_available` function returned False (i.e. the `COURSEWARE_LEARNING_ASSISTANT` `CourseWaffleFlag` was disabled).
Now, the chat view will return a 403 response code if either the `learning_assistant_available` function returns False or if there is a False override in the `LearningAssistantCourseEnabled` model corresponding to the course in which the chat is being requested.
> feat: return 403 if Learning Assistant feature toggle or instructor toggle disabled

- .coveragerc
- docs/decisions/0003-courseapp-use.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/data.py
- learning_assistant/platform_imports.py
- learning_assistant/plugins.py
- learning_assistant/plugins_api.py
- learning_assistant/utils.py
- learning_assistant/views.py
- requirements/base.in
- requirements/base.txt
- requirements/dev.txt
- requirements/doc.txt
- requirements/quality.txt
- requirements/test.txt
- setup.py
- tests/test_api.py
- tests/test_plugins_api.py
- tests/test_utils.py
**Jira**: [COSMO-135](https://2u-internal.atlassian.net/browse/COSMO-135)
**NOTE**: This pull request should not be merged until the configuration modal is added to the [Course Authoring MFE](https://github.com/openedx/frontend-app-course-authoring/tree/master/src/pages-and-resources) for this feature. Please see [COSMO-136](https://2u-internal.atlassian.net/browse/COSMO-136) and [COSMO-137](https://2u-internal.atlassian.net/browse/COSMO-137).
This commit adds a concrete implementation of the `CourseApp` ABC from the `CourseApps` [edx-platform Django app](https://github.com/openedx/edx-platform/tree/d2fd7b2e1fd95baef5fe105d79ead517fe16f20d/openedx/core/djangoapps/course_apps). This enables the Learning Assistant to be represented by a card on the Studio Pages & Resources pages. Please see …
> feat: add CourseApp for Learning Assistant feature and register as entrypoint

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/platform_imports.py
- learning_assistant/plugins_api.py
- test_settings.py
- tests/test_api.py
To prepare for a wider release, the use of a course waffle flag to enable the learning assistant should be replaced by a platform wide django setting. 
If no setting is defined, the feature will default to a disabled state.
> feat: replace waffle flag with setting

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/utils.py
- learning_assistant/views.py
- tests/test_utils.py
If the `context` field is included in the post request to the Xpert Platform backend, the course index will be used. Because the course index does not include all courses in which Xpert LA should be available, we should opt out of using the course index (for now).
> feat: update request to xpert backend

- .github/workflows/ci.yml
**Jira**: None.
This commit fixes the coverage CI action to use the proper Django version to ensure that it runs successfully in CI.
> Fix coverage CI action

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/constants.py
- learning_assistant/utils.py
- learning_assistant/views.py
- tests/test_api.py
- tests/test_utils.py
- tests/test_views.py
Adds an optional `response_variation` parameter when posting to the course chat endpoint to use a different model and/or prompt.
> feat: support variation param for model and prompt

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- tests/test_api.py
Occasionally requests coming from the frontend contain a `null` unit ID. This causes an error, as the null value is interpreted as a string, and then used as a unit ID although it is invalid. Via local testing, I also found that `last` was a unit ID value that could be passed along in the POST request to our Xpert backend. 
To avoid unhandled 500 responses, we should catch the `InvalidKeyError` being thrown, and log when it is happening. The request should still complete successfully, even without a valid unit ID, as content is not necessary for making a successful request.
> fix: handle invalid unit ids

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/views.py
- tests/test_views.py
As part of the experiment clean up, the experimental prompt has been adopted as the "default" prompt. The backend should be updated to now use the default/non-experimental setting.
> feat: use default prompt template

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/constants.py
- learning_assistant/text_utils.py
- learning_assistant/urls.py
- learning_assistant/views.py
- tests/test_api.py
- tests/test_plugins_api.py
- tests/test_views.py
Ticket: https://2u-internal.atlassian.net/browse/COSMO-434
Add GET endpoint to learning-assistant to retrieve message history for a user/course combination.
- Should get messages by user/course combination
- Should add query parameter to limit the amount of messages we receive
> feat: GET endpoint to retrieve message history

- CHANGELOG.rst
- learning_assistant/management/commands/retire_user_messages.py
- learning_assistant/management/commands/tests/test_retire_user_messages.py
This PR adds a management command that can be used to delete messages that have passed an expiration period (defined by `LEARNING_ASSISTANT_MESSAGES_EXPIRY`).
> feat: add management command to remove expired messages

- CHANGELOG.rst
- learning_assistant/__init__.py
The latest version contains a management command to delete user messages, and in order for the management command to be run in the LMS, the latest version of `learning-assistant` needs to be released.
> feat: update release version

- learning_assistant/__init__.py
On the last release I forgot to update the package version. This fixes that for the next release (4.4.3).
> fix: Fixed package version

- learning_assistant/api.py
- learning_assistant/views.py
- tests/test_api.py
When fetching the course history, an error `500` was being produced by the endpoint produced by an `InvalidKeyError`.
This fixes the issue.
> fix: Fixed Couseware History fetching endpoint

- learning_assistant/serializers.py
- tests/test_views.py
In the frontend we are already using the timestamp of the message (although not really showing it).
Instead of making it up on the frontend, I think it's a good moment to add it since it's valuable information for the future.
> feat: Added timestamp to Learning Assistant History response

- CHANGELOG.rst
- learning_assistant/__init__.py
This release contains a Learning Assistant History endpoint fix.
> chore: Release bump to v4.4.4

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/views.py
- tests/test_api.py
- tests/test_views.py
We want the endpoint to return the chat history in ascending order by `timestamp` (creation datetime).
> fix: Updated Learning Assistant History payload to return in ascending order

- learning_assistant/api.py
- learning_assistant/constants.py
- learning_assistant/platform_imports.py
- learning_assistant/views.py
- tests/test_api.py
- tests/test_views.py
Ticket: https://2u-internal.atlassian.net/browse/COSMO-568
Add functionality get or create an audit trial if the user is an audit learner.
- If the user’s course enrollment mode (CourseMode) is audit:
- Get (or create if none exists*) the user’s LearningAssistantAuditTrial (using python API logic created here: https://2u-internal.atlassian.net/browse/COSMO-567 )
- Get remaining days remaining in their Xpert LA audit trial, using endpoint created above
- If remaining days is 0, user should not have access and should return 403
- When an audit learner first sends a message in Xpert LA, we’ll need to create a LearningAssistantAuditTrial to save the start date for the audit trial
> feat: add audit gate to CourseChatView

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/views.py
- tests/test_views.py
Currently, the only logic for the chat history behind the feature flag `learning_assistant.enable_chat_history` is the saving of the messages.
If we want to disable the feature, the chats are no longer being saved but the existing ones will still be returned by the learning Assistant Message History endpoint.
This update makes sure that if the flag for the chat history is disabled, the endpoint would just return an empty list.
> fix: Gates the chat history endpoint behind a waffle flag

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/views.py
- tests/test_views.py
There was a bug in the course chat view causing learning assistant to fail in stage. The course modes were not being concatenated correctly (string and list concatenation), so this PR updates the course modes that are a string to be listified and also updates tests.
> fix: course mode list concatenation issue

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/utils.py
- learning_assistant/views.py
- tests/test_api.py
- tests/test_utils.py
- tests/test_views.py
**Jira**: [COSMO-603](https://2u-internal.atlassian.net/browse/COSMO-603)
In order for the frontend to know the trial length of an audit trial, a `audit_trial_length` attribute is added to the `ChatSummaryView` response as an attribute of the `audit_trial` object.
This property is supplied whether or not a learner has an audit trial. It represents the number of days in an audit trial as currently configured. It does not represent the number of days in the learner's current trial.
> Add  audit_trial_length_days attribute to ChatSummaryView response.

- learning_assistant/admin.py
Correction on the parameters for the expiration_date in https://github.com/edx/learning-assistant/pull/145, which is causing the table to error.
> fix: correct params for expiration_date

- CHANGELOG.rst
- README.rst
Updated setup instructions to include directions for setting up Xpert for audit learners locally.
> docs: update setup instructions

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- learning_assistant/views.py
- tests/test_api.py
[COSMO-616](https://2u-internal.atlassian.net/browse/COSMO-616)
As I was trying to understand how to set the upgrade deadline (i.e. the topic in standup about prioritizing audit vs. honor), I ran into some questions around CourseEnrollment and CourseMode which might change how [audit_trial_is_expired](https://github.com/edx/learning-assistant/blob/39d2f2185e60b2fe17585f1b636f060c75d20eef/learning_assistant/api.py#L310) is implemented.
**Context**
Currently [audit_trial_is_expired](https://github.com/edx/learning-assistant/blob/39d2f2185e60b2fe17585f1b636f060c75d20eef/learning_assistant/api.py#L310) gets the CourseMode (this is where it gets multiple) using the courserun_key and then uses the expiration_datetime (aka upgrade_deadline) to calculate whether the audit trial is expired
But, …
> fix: use course enrollment instead of course mode to calculate audit trial is expired

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/api.py
- tests/test_api.py
This PR fixes a bug which caused an error in audit_trial_is_expired which was happening due to an incompatible comparison in timezone naive and aware datetimes.
Instead of using datetime.now(), we now use timezone.now() from Django utils which makes timezone aware / naive based on the USE_TZ setting. This changes both the instance of this in audit_trial_is_expired and also in the LearningAssistantAuditTrialData's start_date and expiration_date. 
This ensures consistency in the comparisons.
> fix: use django utils timezone to make timezone aware

- CHANGELOG.rst
- learning_assistant/__init__.py
Fixes a linting error on the changelog that prevented the previous release.
> fix: Create release v4.10.1

- .github/workflows/ci.yml
- .github/workflows/pypi-publish.yml
**Description**
Ubuntu 20.04 is losing long term support on 05/31/2025, but the Github Ubuntu 20.04 actions runner image will be fully unsupported on 04/01/2025, and deprecation began on 02/01/2025. The issue link is below.
https://github.com/actions/runner-images/issues/11101
This repository uses the Ubuntu 20.04 LTS runner in two Github actions - ci and pypi-publish. As of 03/04/2025 any new runs of these actions fail with the following error.
This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-01. For more details, see https://github.com/actions/runner-images/issues/11101.
This commit updates the version of the Ubuntu runner from 20.04 to latest.
**Jira**: None.
> Update CI and PyPI publish actions to use ubuntu-latest instead of ubuntu-20.04

- CHANGELOG.rst
- learning_assistant/__init__.py
- learning_assistant/utils.py
[COSMO-682](https://2u-internal.atlassian.net/browse/COSMO-682)
This PR adds lms_language_preference to the Optimizely user context in the backend (this already exists in the frontend), so that the learner is correctly added to the experiment (requires English language users only and audit learners only). 
Then the backend can correctly set the expiration date and trial length, rather than defaulting to 14 days.
> fix: audit trial length defaulting to 14 days in backend

- CHANGELOG.rst
- learning_assistant/__init__.py
This pull request updates the `learning_assistant` plugin to version `4.10.6` and introduces a change to ensure XPert chat API responses are consistently returned as lists for improved compatibility across endpoints.
Version update:
* Updated the version number from `4.10.5` to `4.10.6`.
* Version update for the changes made in PR https://github.com/edx/learning-assistant/pull/190
> chore: Update version to 4.10.6 and document changes in CHANGELOG

- learning_assistant/utils.py
- tests/test_utils.py
This pull request updates the behavior of the `get_chat_response` function in `learning_assistant/utils.py` and modifies related tests in `tests/test_utils.py`. The main change is the removal of logic that converted single objects and error messages into lists. Instead, the function now returns responses as-is, whether they are single objects or lists.
* [`learning_assistant/utils.py`](diffhunk://#diff-85a76b6461766a79ab905e2db9fc871540ebe5d443ea846f3fb5d75e229fee6fL99-R99): Simplified the `get_chat_response` function by removing the conditional logic that converted single objects into lists. Responses are now returned in their original format.
* [`tests/test_utils.py`](diffhunk://#diff-33c13e0b177bacd2f02e29bcb8aea5b49e7ce34901fd8f41fefb65defba1bd33L59-R60): Updated the …
> fix: Simplify chat response handling to return objects as-is instead
